obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.1, 0.12], [0.1, -0.12], [-0.1, -0.12], [-0.1, 0.12]]
inflation_radius: 0.55
transform_tolerance: 0.5

observation_sources: scan
scan:
  data_type: LaserScan
  topic: /ebot/laser/scan
  marking: true
  clearing: true

map_type: costmap

